---
- name: Prepare system
  ansible.builtin._include: prepare.yml
- name: Install NiFi
  ansible.builtin._include: install.yml
- name: Customize NiFi
  ansible.builtin._include: customize.yml
- name: Add NiFi as system service
  ansible.builtin._include: systemd.yml
