---
- name: Prepare system
  ansible.builtin.include: prepare.yml
- name: Install NiFi
  ansible.builtin.include: install.yml
- name: Customize NiFi
  ansible.builtin.include: customize.yml
- name: Add NiFi as system service
  ansible.builtin.include: systemd.yml
