---
- name: Prepare system
  ansible.builtin.import_tasks: prepare.yml
- name: Install NiFi
  ansible.builtin.import_tasks: install.yml
- name: Customize NiFi
  ansible.builtin.import_tasks: customize.yml
- name: Add NiFi as system service
  ansible.builtin.import_tasks: systemd.yml
