---
- name: Prepare system
  ansible.builtin.import_task: prepare.yml
- name: Install NiFi
  ansible.builtin.import_task: install.yml
- name: Customize NiFi
  ansible.builtin.import_task: customize.yml
- name: Add NiFi as system service
  ansible.builtin.import_task: systemd.yml
